import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart';

class DatabaseHelper {
  static DatabaseHelper? _instance;
  static late Database _database;

  DatabaseHelper._privateConstructor();

  static DatabaseHelper get instance {
    _instance ??= DatabaseHelper._privateConstructor();
    return _instance!;
  }

  Future<Database> get database async {
    if (_database.isOpen) return _database;
    _database = await _initDatabase();
    return _database;
  }

  Future<Database> _initDatabase() async {
    String path = join(await getDatabasesPath(), 'words_database.db');
    return await openDatabase(path, version: 1, onCreate: _createDatabase);
  }

  Future<void> _createDatabase(Database db, int version) async {
    await db.execute('''
      CREATE TABLE words(
        id INTEGER PRIMARY KEY,
        word TEXT
      )
    ''');
    // Insert initial words into the database
    for (String word in _initialWords) {
      await db.rawInsert('INSERT INTO words(word) VALUES(?)', [word]);
    }
  }

  final List<String> _initialWords = [
    'ACORN',
    'ADULT',
    'APPLE',
    'APPLY',
    'BEACH',
    'BLOCK',
    'BLOOD',
    'BOARD',
    'BRAIN',
    'BREAD',
    'CHAIN',
    'CHAIR',
    'CHEST',
    'DANCE',
    'EAGER',
    'EARLY',
    'EARTH',
    'ENEMY',
    'ENTRY',
    'ERROR',
    'EVENT',
    'FAITH',
    'FINAL',
    'FLOOR',
    'GREEN',
    'GROUP',
    'GUIDE',
    'HEART',
    'IGLOO',
    'INDIA',
    'INPUT',
    'ISSUE',
    'JAPAN',
    'JUDGE',
    'KNIFE',
    'KNOCK',
    'LIGHT',
    'MAPLE',
    'METAL',
    'MODEL',
    'MONEY',
    'MONTH',
    'MOTOR',
    'OTHER',
    'OWNER',
    'PANEL',
    'PAPER',
    'PARTY',
    'PEACE',
    'QUEEN',
    'RADIO',
    'RANGE',
    'RATIO',
    'REPLY',
    'RIGHT',
    'RIVER',
    'SENSE',
    'SHAPE',
    'SHARE',
    'SHEEP',
    'SHEET',
    'SHIFT',
    'SHIRT',
    'SHOCK',
    'SIGHT',
    'SKILL',
    'SLEEP',
    'SMILE',
    'STAFF',
    'STAGE',
    'START',
    'STATE',
    'STEAM',
    'STEEL',
    'STOCK',
    'STONE',
    'STORE',
    'STUDY',
    'STUFF',
    'STYLE',
    'SUGAR',
    'TABLE',
    'TASTE',
    'THEME',
    'THING',
    'THUMB',
    'UNCLE',
    'UNION',
    'VALUE',
    'VIDEO',
    'VISIT',
    'VOICE',
    'WASTE',
    'WATCH',
    'WATER',
    'WHITE',
    'WOMAN',
    'WORLD',
    'ALARM',
    'ALIVE',
    'ANGER',
    'BASIC',
    'BEAST',
    'BLANK',
    'BLAZE',
    'BLINK',
    'BUNCH',
    'BURST',
    'CATCH',
    'CHALK',
    'CLOUD',
    'COLOR',
    'CRISP',
    'DELAY',
    'DREAM',
    'DRIVE',
    'EAGLE',
    'ELBOW',
    'EMBRY',
    'FIGHT',
    'FLAME',
    'FRESH',
    'GLAZE',
    'GRASP',
    'GREET',
    'HATCH',
    'HEDGE',
    'HONEY',
    'IDEAL',
    'IMAGE',
    'JELLY',
    'JOKER',
    'LEMON',
    'LIGHT',
    'LOYAL',
    'MAGIC',
    'MICRO',
    'NOISE',
    'NOVEL',
    'OASIS',
    'ONION',
    'PANEL',
    'PIXEL',
    'PLANT',
    'PLUMB',
    'PRIDE',
    'QUEER',
    'QUIET',
    'RANCH',
    'READY',
    'ROAST',
    'SAUCE',
    'SCARF',
    'SCRUB',
    'SHADE',
    'SHINY',
    'SLEEP',
    'SOLID',
    'SPEAK',
    'SPORT',
    'STAIN',
    'SWEEP',
    'TABLE',
    'TIGER',
    'TRACE',
    'TRUTH',
    'UNCLE',
    'UNITY',
    'VIVID',
    'WOUND',
    'YIELD',
    'YOUTH',
    'ZEBRA',
    'ANGEL',
    'APRIL',
    'ARROW',
    'BIRCH',
    'CAMEL',
    'CANDY',
    'CLOVE',
    'CRAFT',
    'DIVER',
    'DRIFT',
    'EIGHT',
    'EPOCH',
    'FAIRY',
    'FIBER',
    'FLUTE',
    'GRACE',
    'GRAIN',
    'HUMOR',
    'JEWEL',
    'LAUGH',
    'LOGIC',
    'MANGO',
    'MUSIC',
    'NOBLE',
    'OLIVE',
    'PEACH',
    'PEAKS',
    'PIZZA',
    'QUOTE',
    'RIVER',
    'ROBOT',
    'SHARK',
    'SHELL',
    'SHINE',
    'SMILE',
    'SPEAR',
    'SPIRE'
  ];

  Future<List<String>> getWords() async {
    final Database db = await database;
    final List<Map<String, dynamic>> maps = await db.query('words');
    return List.generate(maps.length, (i) {
      return maps[i]['word'];
    });
  }
}
